version: '3.8'
services:
  sadtalker:
    image: paidax/faster-sadtalker-api:0.1.3
    container_name: sadtalker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./checkpoints:/home/SadTalker/checkpoints
      - ./gfpgan/weights:/home/SadTalker/gfpgan/weights
      - ./results:/home/SadTalker/results
    ports:
      - 10364:10364
    environment:
      - TTS_SERVER=http://tts:9566/tts
    command: uvicorn main:app --reload --port 10364 --host 0.0.0.0
  tts:
    container_name: tts
    image: paidax/tts_modelscope:0.1.3
    ports:
      - 9566:9566
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: uvicorn main:app --reload --port 9566 --host 0.0.0.0
